products/urls.py
from django.urls import path
from . import views

app_name = 'products'
urlpatterns = [
    path('', views.index_view, name='index'),
    path('product_<int:product_id>/', views.product_view, name='product'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout')
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('shop/', include('products.urls')),
    path('admin/', admin.site.urls),
]

products/models.py
from django.db import models


class Product(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=9, decimal_places=2)
    available = models.BooleanField(default=True)

    def __str__(self):
        return self.title

products/forms.py
from django import forms
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError('Invalid username')

        user = User.objects.get(username=username)
        if user and not user.check_password(password):
            raise forms.ValidationError('Invalid password')

products/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

from .models import Product
from .forms import LoginForm


def index_view(request):
    products_list = Product.objects.order_by('id')
    context = {
        'products_list': products_list
    }
    return render(request, 'products/index.html', context)


def product_view(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    return render(request, 'products/product.html', {'product': product})


def login_view(request):
    form = LoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        login_user = authenticate(username=username, password=password)
        if login_user:
            login(request, login_user)
            return HttpResponseRedirect(reverse('products:index'))
    return render(request, 'products/login.html', {'form': form})


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('products:index'))

products/templates/products/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>
            {% block page_title %}
                Page Title
            {% endblock %}
        </title>
    </head>
    <body>
        {% if request.user.is_authenticated %}
            <p>Hello, {{ user.username }}</p>
            <a href="{% url 'products:logout' %}">Logout</a>
        {% else %}
            <p>Hello, guest!</p>
            <a href="{% url 'products:login' %}">Login</a>
        {% endif %}

        {% block content_title %}
            Title
        {% endblock %}

        {% block content %}
            Content
        {% endblock %}
    </body>
</html>

products/templates/products/index.html
{% extends 'products/base.html' %}

{% block page_title %}
    Products List
{% endblock %}

{% block content_title %}
    <h3>Main</h3>
{% endblock %}

{% block content %}
    {% if products_list %}
        <ul>
            {% for product in products_list%}
            <li><a href="{% url 'products:product' product.id%}">{{ product.title }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Soon...</p>
    {% endif %}
{% endblock %}

products/templates/products/login.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Login</title>

    </head>
    <body>
        <h3>Login</h3>

        <form action="" method="POST">
            {% csrf_token %}
        
            {{ form.as_p }}

            <input type="submit" value='Login' />
        </form>
    </body>
</html>

products/templates/products/product.html
{% extends 'products/base.html' %}

{% block page_title %}
    {{ product.title }}
{% endblock %}

{% block content_title %}
    <h3>{{ product.title }}</h3>
{% endblock %}

{% block content %}
    <p>{{ product.description }}</p>
    <p>Price: {{ product.price }}$</p>
{% endblock %}